// Code generated by "stringer -type=ArgType"; DO NOT EDIT

package nash

import "fmt"

const _ArgType_name = "ArgQuotedArgUnquotedArgVariableArgNumberArgListArgConcat"

var _ArgType_index = [...]uint8{0, 9, 20, 31, 40, 47, 56}

func (i ArgType) String() string {
	i -= 1
	if i < 0 || i >= ArgType(len(_ArgType_index)-1) {
		return fmt.Sprintf("ArgType(%d)", i+1)
	}
	return _ArgType_name[_ArgType_index[i]:_ArgType_index[i+1]]
}
