// Code generated by "stringer -type=itemType"; DO NOT EDIT

package nash

import "fmt"

const _itemType_name = "itemErroritemEOFitemBuiltinitemImportitemCommentitemSetEnvitemShowEnvitemVarNameitemAssignitemAssignCmditemConcatitemVariableitemListOpenitemListCloseitemListElemitemCommanditemBindFnitemArgitemLeftBlockitemRightBlockitemLeftParenitemRightParenitemStringitemRedirRightitemRedirRBracketitemRedirLBracketitemRedirFileitemRedirNetAddritemRedirMapEqualitemRedirMapLSideitemRedirMapRSideitemIfitemElseitemComparisonitemRforkitemRforkFlagsitemCditemFnDeclitemFnInv"

var _itemType_index = [...]uint16{0, 9, 16, 27, 37, 48, 58, 69, 80, 90, 103, 113, 125, 137, 150, 162, 173, 183, 190, 203, 217, 230, 244, 254, 268, 285, 302, 315, 331, 348, 365, 382, 388, 396, 410, 419, 433, 439, 449, 458}

func (i itemType) String() string {
	i -= 2
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i+2)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
