// Code generated by "stringer -type=itemType"; DO NOT EDIT

package nash

import "fmt"

const _itemType_name = "itemErroritemEOFitemImportitemCommentitemSetEnvitemShowEnvitemVarNameitemAssignitemAssignCmditemConcatitemVariableitemListOpenitemListCloseitemListElemitemCommanditemArgitemLeftBlockitemRightBlockitemLeftParenitemRightParenitemStringitemRedirRightitemRedirRBracketitemRedirLBracketitemRedirFileitemRedirNetAddritemRedirMapEqualitemRedirMapLSideitemRedirMapRSideitemIfitemElseitemComparisonitemRforkitemRforkFlagsitemCditemFnDeclitemFnInv"

var _itemType_index = [...]uint16{0, 9, 16, 26, 37, 47, 58, 69, 79, 92, 102, 114, 126, 139, 151, 162, 169, 182, 196, 209, 223, 233, 247, 264, 281, 294, 310, 327, 344, 361, 367, 375, 389, 398, 412, 418, 428, 437}

func (i itemType) String() string {
	i -= 2
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i+2)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
