// Code generated by "stringer -type=NodeType"; DO NOT EDIT

package nash

import "fmt"

const _NodeType_name = "NodeSetAssignmentNodeShowEnvNodeAssignmentNodeCmdAssignmentNodeImportNodeCommandNodeArgNodeStringNodeRforkNodeCdNodeRforkFlagsNodeIfNodeCommentNodeFnDeclNodeFnInvNodeBindFn"

var _NodeType_index = [...]uint8{0, 17, 28, 42, 59, 69, 80, 87, 97, 106, 112, 126, 132, 143, 153, 162, 172}

func (i NodeType) String() string {
	i -= 1
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return fmt.Sprintf("NodeType(%d)", i+1)
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
