// Code generated by "stringer -type=NodeType"; DO NOT EDIT

package nash

import "fmt"

const _NodeType_name = "NodeSetAssignmentNodeAssignmentNodeCommandNodeArgNodeElemNodeStringNodeRforkNodeCdNodeRforkFlagsNodeComment"

var _NodeType_index = [...]uint8{0, 17, 31, 42, 49, 57, 67, 76, 82, 96, 107}

func (i NodeType) String() string {
	i -= 1
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return fmt.Sprintf("NodeType(%d)", i+1)
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
