// Code generated by "stringer -type=objType"; DO NOT EDIT

package sh

import "fmt"

const _objType_name = "StringTypeFnTypeListType"

var _objType_index = [...]uint8{0, 10, 16, 24}

func (i objType) String() string {
	i -= 1
	if i < 0 || i >= objType(len(_objType_index)-1) {
		return fmt.Sprintf("objType(%d)", i+1)
	}
	return _objType_name[_objType_index[i]:_objType_index[i+1]]
}
