// Code generated by "stringer -type=NodeType"; DO NOT EDIT

package ast

import "fmt"

const _NodeType_name = "NodeSetAssignmentNodeAssignmentNodeCmdAssignmentNodeImportNodeCommandNodePipeNodeArgNodeStringNodeRforkNodeCdNodeRforkFlagsNodeIfNodeCommentNodeFnDeclNodeReturnNodeFnInvNodeBindFnNodeDumpNodeForNodeBuiltin"

var _NodeType_index = [...]uint8{0, 17, 31, 48, 58, 69, 77, 84, 94, 103, 109, 123, 129, 140, 150, 160, 169, 179, 187, 194, 205}

func (i NodeType) String() string {
	i -= 1
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return fmt.Sprintf("NodeType(%d)", i+1)
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
