// Code generated by "stringer -type=NodeType"; DO NOT EDIT

package ast

import "fmt"

const _NodeType_name = "NodeSetenvNodeBlockNodeNameNodeAssignmentNodeExecAssignNodeExecMultipleAssignNodeImportexecBeginNodeCommandNodePipeNodeRedirectNodeFnInvexecEndexpressionBeginNodeStringExprNodeIntExprNodeVarExprNodeListExprNodeIndexExprNodeConcatExprexpressionEndNodeStringNodeRforkNodeRforkFlagsNodeIfNodeCommentNodeFnDeclNodeReturnNodeBindFnNodeDumpNodeFor"

var _NodeType_index = [...]uint16{0, 10, 19, 27, 41, 55, 77, 87, 96, 107, 115, 127, 136, 143, 158, 172, 183, 194, 206, 219, 233, 246, 256, 265, 279, 285, 296, 306, 316, 326, 334, 341}

func (i NodeType) String() string {
	i -= 1
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return fmt.Sprintf("NodeType(%d)", i+1)
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
